# data/artists_data.py

ARTISTS = [
    {
        "slug": "lin-yuxuan",
        "name": "林語璇",
        "subtitle": "甜感清新系｜商業活動與品牌露出都很穩",
        "positioning": "清新甜感",
        "strengths": "舞台互動、粉絲經營、平面拍攝",
        "tags": ["跨國", "可商業化", "可活動", "短影音"],
        "cover": "images/artists/demo_1.jpg",
    },
    {
        "slug": "chen-jingyi",
        "name": "陳靜宜",
        "subtitle": "高級感氣場｜適合精品、形象代言與媒體採訪",
        "positioning": "高級質感",
        "strengths": "形象拍攝、品牌代言、訪談",
        "tags": ["可商業化", "短影音", "主持"],
        "cover": "images/artists/demo_2.jpg",
    },
    {
        "slug": "huang-ruoting",
        "name": "黃若庭",
        "subtitle": "元氣熱血系｜球場活動、現場帶動超強",
        "positioning": "元氣熱血",
        "strengths": "現場控場、球場應援、活動帶動",
        "tags": ["可活動", "可商業化"],
        "cover": "images/artists/demo_3.jpg",
    },
    {
        "slug": "wu-xinyi",
        "name": "吳心宜",
        "subtitle": "知性親和｜適合主持、品牌直播、互動型合作",
        "positioning": "知性親和",
        "strengths": "主持、直播、口條",
        "tags": ["主持", "可商業化"],
        "cover": "images/artists/demo_4.jpg",
    },
    {
        "slug": "li-ruoxi",
        "name": "李若熙",
        "subtitle": "甜酷反差｜短影音爆發力強、話題度高",
        "positioning": "甜酷反差",
        "strengths": "短影音、舞蹈、話題操作",
        "tags": ["短影音", "可商業化"],
        "cover": "images/artists/demo_5.jpg",
    },
    {
        "slug": "zhang-yuting",
        "name": "張語婷",
        "subtitle": "溫柔治癒系｜適合生活品牌、餐飲、開箱合作",
        "positioning": "溫柔治癒",
        "strengths": "開箱、生活風格、社群互動",
        "tags": ["可商業化", "短影音"],
        "cover": "images/artists/demo_6.jpg",
    },
    {
        "slug": "su-peiling",
        "name": "蘇佩玲",
        "subtitle": "舞台型女王｜大型舞台、記者會、活動效果拉滿",
        "positioning": "舞台氣場",
        "strengths": "舞台表演、活動視覺、鏡頭感",
        "tags": ["可活動", "可商業化", "跨國"],
        "cover": "images/artists/demo_7.jpg",
    },
    {
        "slug": "yang-xuanxuan",
        "name": "楊萱萱",
        "subtitle": "鄰家系吸粉｜品牌互動、粉絲轉換表現佳",
        "positioning": "鄰家親和",
        "strengths": "粉絲經營、合照互動、短影音",
        "tags": ["可商業化", "短影音", "可活動"],
        "cover": "images/artists/demo_8.jpg",
    },
    {
        "slug": "zhou-yunhan",
        "name": "周韻涵",
        "subtitle": "跨國合作友善｜台韓活動整合、雙語溝通順",
        "positioning": "跨國整合",
        "strengths": "跨國活動、雙語溝通、媒體配合",
        "tags": ["跨國", "可商業化", "可活動"],
        "cover": "images/artists/demo_9.jpg",
    },
    {
        "slug": "lin-kexin",
        "name": "林可欣",
        "subtitle": "笑容系主場｜適合商場活動、路演、粉絲見面會",
        "positioning": "笑容感染力",
        "strengths": "活動互動、路演、見面會",
        "tags": ["可活動", "可商業化"],
        "cover": "images/artists/demo_10.jpg",
    },
]
